/* eslint-disable */
/**
 * Generated `api` utility for @vantageos/data-lake component internals.
 *
 * Runtime shim — real typed file generated by `npx convex dev` when host mounts this component.
 * This version provides runtime-compatible exports for Convex bundler.
 * @module
 */

import { anyApi, componentsGeneric } from "convex/server";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = anyApi;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const internal: any = anyApi;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const components: any = componentsGeneric();
